name: Rust

on:
  push:
    tags:
    - 'v*' # Trigger the workflow on new tags starting with 'v'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build release
      run: cargo build --release --verbose
      id: create_release
    - name: Package Release
      run: zip -j release.zip target/release/bedrust
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
